import type { ModelCapability, ModelId, ModelInfo, ProviderId } from './types.mts'

const cap = (
  reasoning: number,
  coding: number,
  frontend: number,
  backend: number,
  documentation: number,
  vision: boolean,
  tools: boolean,
): ModelCapability => ({ reasoning, coding, frontend, backend, documentation, vision, tools })

/**
 * Catálogo de modelos simulados. Los precios y puntuaciones son estimaciones
 * locales deterministas. Ninguna llamada a APIs reales.
 */
export const MODEL_CATALOG: ReadonlyArray<ModelInfo> = [
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'openai',
    type: 'chat',
    capabilities: cap(4, 4, 4, 4, 4, true, true),
    contextWindow: 128000,
    speed: 4,
    pricing: { currency: 'USD', per1kInput: 0.005, per1kOutput: 0.015, creditsPer1kInput: 0.5 },
  },
  {
    id: 'gpt-4.1',
    name: 'GPT-4.1',
    provider: 'openai',
    type: 'chat',
    capabilities: cap(4, 4, 4, 4, 4, true, true),
    contextWindow: 1048576,
    speed: 4,
    pricing: { currency: 'USD', per1kInput: 0.002, per1kOutput: 0.008, creditsPer1kInput: 0.2 },
  },
  {
    id: 'o3-mini',
    name: 'o3-mini',
    provider: 'openai',
    type: 'reasoning',
    capabilities: cap(5, 5, 3, 5, 3, false, true),
    contextWindow: 200000,
    speed: 4,
    pricing: { currency: 'USD', per1kInput: 0.0011, per1kOutput: 0.0044, creditsPer1kInput: 0.11 },
  },
  {
    id: 'claude-sonnet-4',
    name: 'Claude Sonnet 4',
    provider: 'anthropic',
    type: 'chat',
    capabilities: cap(5, 5, 5, 5, 5, true, true),
    contextWindow: 200000,
    speed: 4,
    pricing: { currency: 'USD', per1kInput: 0.003, per1kOutput: 0.015, creditsPer1kInput: 0.3 },
  },
  {
    id: 'claude-haiku-4',
    name: 'Claude Haiku 4',
    provider: 'anthropic',
    type: 'chat',
    capabilities: cap(3, 4, 3, 4, 4, true, true),
    contextWindow: 200000,
    speed: 5,
    pricing: { currency: 'USD', per1kInput: 0.001, per1kOutput: 0.005, creditsPer1kInput: 0.1 },
  },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'google',
    type: 'chat',
    capabilities: cap(5, 4, 4, 4, 4, true, true),
    contextWindow: 1048576,
    speed: 4,
    pricing: { currency: 'USD', per1kInput: 0.00125, per1kOutput: 0.01, creditsPer1kInput: 0.125 },
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'google',
    type: 'chat',
    capabilities: cap(4, 4, 3, 4, 3, true, true),
    contextWindow: 1048576,
    speed: 5,
    pricing: { currency: 'USD', per1kInput: 0.0003, per1kOutput: 0.0025, creditsPer1kInput: 0.03 },
  },
  {
    id: 'openrouter-auto',
    name: 'OpenRouter Auto',
    provider: 'openrouter',
    type: 'chat',
    capabilities: cap(4, 4, 4, 4, 4, true, true),
    contextWindow: 128000,
    speed: 4,
    pricing: { currency: 'USD', per1kInput: 0, per1kOutput: 0, creditsPer1kInput: 0 },
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'deepseek',
    type: 'reasoning',
    capabilities: cap(5, 5, 3, 5, 3, false, false),
    contextWindow: 128000,
    speed: 3,
    pricing: { currency: 'USD', per1kInput: 0.00055, per1kOutput: 0.00219, creditsPer1kInput: 0.055 },
  },
  {
    id: 'deepseek-v3',
    name: 'DeepSeek V3',
    provider: 'deepseek',
    type: 'chat',
    capabilities: cap(4, 4, 4, 4, 3, false, true),
    contextWindow: 128000,
    speed: 3,
    pricing: { currency: 'USD', per1kInput: 0.00027, per1kOutput: 0.0011, creditsPer1kInput: 0.027 },
  },
  {
    id: 'mistral-large',
    name: 'Mistral Large',
    provider: 'mistral',
    type: 'chat',
    capabilities: cap(4, 4, 3, 4, 3, false, true),
    contextWindow: 128000,
    speed: 4,
    pricing: { currency: 'USD', per1kInput: 0.002, per1kOutput: 0.006, creditsPer1kInput: 0.2 },
  },
  {
    id: 'codestral',
    name: 'Codestral',
    provider: 'mistral',
    type: 'code',
    capabilities: cap(3, 5, 3, 5, 3, false, true),
    contextWindow: 256000,
    speed: 4,
    pricing: { currency: 'USD', per1kInput: 0.0003, per1kOutput: 0.0009, creditsPer1kInput: 0.03 },
  },
  {
    id: 'groq-llama-3.3',
    name: 'Llama 3.3 70B (Groq)',
    provider: 'groq',
    type: 'chat',
    capabilities: cap(3, 3, 3, 3, 3, false, true),
    contextWindow: 131072,
    speed: 5,
    pricing: { currency: 'USD', per1kInput: 0.00059, per1kOutput: 0.00079, creditsPer1kInput: 0.059 },
  },
  {
    id: 'groq-mixtral',
    name: 'Mixtral 8x7B (Groq)',
    provider: 'groq',
    type: 'chat',
    capabilities: cap(3, 3, 2, 3, 2, false, false),
    contextWindow: 32768,
    speed: 5,
    pricing: { currency: 'USD', per1kInput: 0.00024, per1kOutput: 0.00024, creditsPer1kInput: 0.024 },
  },
  {
    id: 'llama-3.1',
    name: 'Llama 3.1 8B',
    provider: 'ollama',
    type: 'chat',
    capabilities: cap(2, 2, 2, 2, 2, false, false),
    contextWindow: 131072,
    speed: 3,
    pricing: { currency: 'USD', per1kInput: 0, per1kOutput: 0, creditsPer1kInput: 0 },
  },
  {
    id: 'llama-4-scout',
    name: 'Llama 4 Scout',
    provider: 'lm-studio',
    type: 'chat',
    capabilities: cap(3, 3, 3, 3, 3, true, false),
    contextWindow: 10000000,
    speed: 3,
    pricing: { currency: 'USD', per1kInput: 0, per1kOutput: 0, creditsPer1kInput: 0 },
  },
  {
    id: 'qwen-coder',
    name: 'Qwen Coder',
    provider: 'together',
    type: 'code',
    capabilities: cap(3, 4, 3, 4, 2, false, true),
    contextWindow: 131072,
    speed: 4,
    pricing: { currency: 'USD', per1kInput: 0.00018, per1kOutput: 0.00018, creditsPer1kInput: 0.018 },
  },
  {
    id: 'gpt-image',
    name: 'GPT Image',
    provider: 'v0',
    type: 'image',
    capabilities: cap(1, 1, 5, 1, 1, true, false),
    contextWindow: 16000,
    speed: 3,
    pricing: { currency: 'USD', per1kInput: 0, per1kOutput: 0, creditsPer1kInput: 2 },
  },
  {
    id: 'azure-gpt-4o',
    name: 'GPT-4o (Azure)',
    provider: 'azure-openai',
    type: 'chat',
    capabilities: cap(4, 4, 4, 4, 4, true, true),
    contextWindow: 128000,
    speed: 4,
    pricing: { currency: 'USD', per1kInput: 0.005, per1kOutput: 0.015, creditsPer1kInput: 0.5 },
  },
  {
    id: 'github-gpt-4o-mini',
    name: 'GPT-4o mini (GitHub Models)',
    provider: 'github-models',
    type: 'chat',
    capabilities: cap(3, 3, 3, 3, 3, true, true),
    contextWindow: 128000,
    speed: 5,
    pricing: { currency: 'USD', per1kInput: 0.00015, per1kOutput: 0.0006, creditsPer1kInput: 0.015 },
  },
]

/** Busca un modelo por id o devuelve null. */
export function getModelInfo(id: ModelId): ModelInfo | null {
  return MODEL_CATALOG.find((model) => model.id === id) ?? null
}

/** Devuelve los modelos de un proveedor. */
export function getModelsByProvider(provider: ProviderId): ReadonlyArray<ModelInfo> {
  return MODEL_CATALOG.filter((model) => model.provider === provider)
}
